# Generated by Django 3.2.11 on 2022-01-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('hindi_name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('visibilityType', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='Public', max_length=20)),
                ('recipeType', models.CharField(choices=[('V', 'Vegetarian'), ('NV', 'Non-Vegetarian'), ('VE', 'Vegan')], max_length=20)),
                ('mealType', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack'), ('DE', 'Dessert')], max_length=20)),
                ('servingSize', models.PositiveSmallIntegerField()),
                ('cookingTime', models.PositiveIntegerField()),
                ('steps', models.JSONField()),
                ('picture', models.URLField(default='https://raw.githubusercontent.com/shrey1098/img/main/462773.jpg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'steps', 'picture')},
            },
        ),
        migrations.CreateModel(
            name='userIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='viewedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='savedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='likedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
