# Generated by Django 3.2.4 on 2021-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servingSize',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
