# Generated by Django 3.2.4 on 2021-06-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.URLField(default=None),
        ),
    ]
