# Generated by Django 3.2.4 on 2021-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
    ]
