# Generated by Django 3.2.4 on 2021-06-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedrecipe',
            old_name='name',
            new_name='recipeName',
        ),
    ]
