# Generated by Django 3.2.4 on 2021-06-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_name_savedrecipe_recipename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedrecipe',
            old_name='recipeName',
            new_name='name',
        ),
    ]
