# Generated by Django 3.2.4 on 2021-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_recipename_savedrecipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servingSize',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
