# Generated by Django 3.2.4 on 2021-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_recipe_servingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default={'name': 'something'}),
            preserve_default=False,
        ),
    ]
