# Generated by Django 3.2.4 on 2021-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210624_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
