# Generated by Django 3.2.4 on 2021-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_recipe_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
